config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sudokus do
    member do
      post :solve
    end
  end
  
  resources :sessions, only:      [:new, :create, :destroy]
  resources :microposts, only:    [:create, :destroy]
  resources :relationships, only: [:create, :destroy] 

  root to: 'static_pages#home'

  match '/sender', to: 'static_pages#sender'
  match '/test', to: 'static_pages#test', via: :post
  match '/record', to: 'static_pages#record', via: :post
  match '/maps',  to: 'static_pages#maps'
  match '/sudoku',  to: 'sudokus#new'
  match '/signup',  to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help' => 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/sudoku.rb
class Sudoku < ActiveRecord::Base
  validates :content, :presence => { :in => true, :message => "error --puzzle must have a name" }

  attr_accessible :content, :big_grid
  serialize :big_grid
  
  def apply_rules
    return rule_4 || rule_1 || rule_2 || rule_3
  end # apply_rules

  def rule_1
    
    # return value is hash with :rule => String and :locations => Array
    # used to build up lists of rules used and locations solved
    
    9.times do |number_index|
      number = number_index + 1

      9.times do |current_cube_number|
        if (all_possible_spots_in_cube(number, current_cube_number) == 1)

          winner_location = first_possible_spot_in_cube(number, current_cube_number)
          big_grid[winner_location][:value] = number
          big_grid[winner_location][:possibilities] = []

          erase_possibilities(number, current_cube_number)
          
          return { 
            rule_text: "Rule 1:  Pick a 3x3 cube and pick a number.  If there 
          is only 1 spot in that cube where that number can go (based on other numbers 
          filled in, but not possibilities recorded), fill it in.", 
            locations: [winner_location]
          }
        end # if
      end # 9.times do

    end # 9.times do
    
    return false
  end # rule_1

  def rule_2

    9.times do |number_index|
      number = number_index + 1

      9.times do |current_cube_number|
        if (all_possible_spots_in_cube(number, current_cube_number) == 2)
          
          winner_location1 = first_possible_spot_in_cube(number,current_cube_number)
          winner_location2 = second_possible_spot_in_cube(number,current_cube_number)

          unless big_grid[winner_location1][:possibilities].include?(number)
            big_grid[winner_location1][:possibilities] << number
            big_grid[winner_location2][:possibilities] << number
            return { 
              rule_text: "Rule 2:  Pick a number and pick a cube.  If there are exactly 2 spots in the cube 
              where that number can go, record them as possibilities (indicated by small text).",
              locations: [winner_location1, winner_location2]
            }
          end # unless
                    
        end # if 
      end # 9.times do |current_cube_number
      
    end # 9.times do |number_index|
                    
    return false 
  end # rule_2

  def rule_3
    
    9.times do |number_index|
      number = number_index + 1

      9.times do |current_cube_number|
        if (all_possible_spots_in_cube_complex(number, current_cube_number) == 1)
          
          winner_location = first_possible_spot_in_cube_complex(number, current_cube_number)
          big_grid[winner_location][:value] = number
          big_grid[winner_location][:possibilities] = []

          erase_possibilities(number, current_cube_number)

          return { 
            rule_text: "Rule 3:  Pick a number and pick a cube.  If there is only spot in the cube 
            where that number can go (considering numbers filled in AND possibilities recorded), 
            fill in that spot.  Erase all possibilities in that spot.  Erase anywhere else 
            in that cube that number was listed as a possibility.",
            locations: [winner_location]
          }
            
        end # if
      end # 9.times do
    end # 9.times do
            
    return false
    
  end # rule_3

  def rule_4
    9.times do |number_index|
      number = number_index + 1
  
      9.times do |current_cube_number|
        items = cube_objects_by_number(current_cube_number)
        times_found = 0
        winner_location = 81
        
        items.each do |item|
          if item[:possibilities].include?(number)
            times_found += 1
            winner_location = item[:location]
          end # if
        end # do
      
        if times_found == 1
          big_grid[winner_location][:value] = number
          big_grid[winner_location][:possibilities] = []
          return { 
            rule_text: "Rule 4:  Pick a number and pick a cube.  If that number appears 
            as a possibility in just 1 spot in that cube, fill in that spot with that 
            number.  Erase all possibilities in that spot.",
            locations: [winner_location]
          }
        end # if
      end # 9.times do
    end # 9.times do
  
    return false
  end # rule_4
  
  def solved
    return false if !self.big_grid
    self.big_grid.each do |item|
      return false if !item[:value]
    end
    return true
  end
  
  def erase_possibilities(number, cube_number)
    locations = cube_locations_by_number(cube_number)
  
    locations.each do |location|
      big_grid[location][:possibilities].length.times do |i|
        if big_grid[location][:possibilities][i] == number
          big_grid[location][:possibilities][i] = nil
        end
      end
    end
  end

  def first_possible_spot_in_cube(number, cube_number)
    locations_in_cube = cube_locations_by_number(cube_number)
    locations_in_cube.each do |location|
      return location if (can_go_in_spot(number,location))
    end

    return 81 # error tracking; should never get to this line
  end

  def first_possible_spot_in_cube_complex(number, cube_number)
    locations_in_cube = cube_locations_by_number(cube_number)
    locations_in_cube.each do |location|
      return location if (can_go_in_spot_complex(number,location))
    end

    return 81 # error tracking; should never get to this line
  end


  def second_possible_spot_in_cube(number, cube_number)
    locations_in_cube = cube_locations_by_number(cube_number)
    
    locations_in_cube.each do |location|
      return location if  can_go_in_spot(number,location) && 
                          !(first_possible_spot_in_cube(number, cube_number)==location)
    end

    return 81 # error tracking; should never get to this line
  end
  
  def all_possible_spots_in_cube(number, cube_number)
    spots = 0
    locations_in_cube = cube_locations_by_number(cube_number)

    locations_in_cube.each do |location|
      spots += 1 if (can_go_in_spot(number, location))
    end

    return spots
  end
  
  def all_possible_spots_in_cube_complex(number, cube_number)
    spots = 0
    locations_in_cube = cube_locations_by_number(cube_number)
    
    locations_in_cube.each do |location|
      spots += 1 if (can_go_in_spot_complex(number, location))
    end
    
    return spots
  end

  def can_go_in_spot(number, location)
    return !( column_values_by_location(location).include?(number) || 
              row_values_by_location(location).include?(number) ||
              cube_values_by_location(location).include?(number) ||
              big_grid[location][:value])
  end
  
  def can_go_in_spot_complex(number, location)
    return (can_go_in_spot(number, location) && 
            can_go_in_row_complex(number, location) && 
            can_go_in_column_complex(number, location))
  end
  
  def can_go_in_row_complex(number, location)
    row_items = row_items_by_location(location)
    items_matching_possibility = []
    
    row_items.each do |item|
      if item[:possibilities].include?(number)
        items_matching_possibility.each do |possible|
          if (cube_number_by_location(possible[:location]) == cube_number_by_location(item[:location]) &&
              cube_number_by_location(possible[:location]) != cube_number_by_location(location))
            return false
          end
        end
        items_matching_possibility << item
      end
    end
    
    return true
  end

  def can_go_in_column_complex(number, location)
    col_items = column_items_by_location(location)
    items_matching_possibility = []
    
    col_items.each do |item|
      if item[:possibilities].include?(number)
        items_matching_possibility.each do |possible|
          if (cube_number_by_location(possible[:location]) == cube_number_by_location(item[:location]) &&
              cube_number_by_location(possible[:location]) != cube_number_by_location(location))
            return false
          end
        end
        items_matching_possibility << item
      end
    end
    
    return true
  end

  def cube_locations_by_number(number)
    start_location = cube_start_location_by_number(number)
    cube_locations = Array.new(9)
    
    9.times do |i|
      cube_locations[i] = start_location
      if (i%3 == 2) 
        start_location += 7
      else
        start_location += 1
      end
    end
    
    return cube_locations
  end

  def cube_number_by_location(location)
      return 0 if (location % 9 < 3 && location < 27)
      return 1 if (location % 9 > 2 && location % 9 < 6 && location < 27)
      return 2 if (location % 9 > 5 && location < 27)
      return 3 if (location % 9 < 3 && location > 26 && location < 54)
      return 4 if (location % 9 > 2 && location % 9 < 6 && location > 26 && location < 54)
      return 5 if (location % 9 > 5 && location > 26 && location < 54)
      return 6 if (location % 9 < 3 && location > 53)
      return 7 if (location % 9 > 2 && location % 9 < 6 && location > 53)
      return 8 if (location % 9 > 5 && location > 53)
    end

  def cube_values_by_location(location)
    return cube_values_by_number(0) if (location % 9 < 3 && location < 27)
    return cube_values_by_number(1) if (location % 9 > 2 && location % 9 < 6 && location < 27)
    return cube_values_by_number(2) if (location % 9 > 5 && location < 27)
    return cube_values_by_number(3) if (location % 9 < 3 && location > 26 && location < 54)
    return cube_values_by_number(4) if (location % 9 > 2 && location % 9 < 6 && location > 26 && location < 54)
    return cube_values_by_number(5) if (location % 9 > 5 && location > 26 && location < 54)
    return cube_values_by_number(6) if (location % 9 < 3 && location > 53)
    return cube_values_by_number(7) if (location % 9 > 2 && location % 9 < 6 && location > 53)
    return cube_values_by_number(8) if (location % 9 > 5 && location > 53)
  end

app/controllers/sudokus_controller.rb
class SudokusController < ApplicationController
  
  def new
    @sudoku = Sudoku.new
  end

  def create
    @sudoku = 
      case params[:create]
      when "original"
        Sudoku.createDefault(params[:sudoku])
      when "random"
        Sudoku.createRandom(params[:sudoku])
      else
        Sudoku.create(params[:sudoku])
      end

    if @sudoku.save

      # for custom sudoku
      if @sudoku.big_grid.nil?
        redirect_to edit_sudoku_path(@sudoku)
      else
        flash[:just_created] = true
        redirect_to sudoku_path(@sudoku)
      end
    else
      render new_sudoku_path
    end
  end
  
  def edit
    @sudoku = Sudoku.find(params[:id])
  end
  
  def solve
    @sudoku = Sudoku.find(params[:id])
    rules_used = []
    locations_updated = []
    File.open(
'/Users/jamesharris/rails_projects/sample_app/app/views/static_pages/test.txt', 'a') do |f|
    	f.puts "solver"
    	f.puts "solve"
    end
    

    if params[:solve_this_many] == "all"
      until @sudoku.solved
        rule_results = @sudoku.apply_rules
        
        # apply_rules returned false means rules didn't work
        break unless rule_results
        
        rules_used.push(rule_results[:rule_text]) unless rules_used.include?(rule_results[:rule_text])
        rule_results[:locations].each { |location| locations_updated.push(location) }
        # locations_updated.push(rule_results[:location])
      end
    else    
      params[:solve_this_many].to_i.times do
        rule_results = @sudoku.apply_rules
        
        # apply_rules returned false means rules didn't work
        break unless rule_results
        
        rules_used.push(rule_results[:rule_text]) unless rules_used.include?(rule_results[:rule_text])
        rule_results[:locations].each { |location| locations_updated.push(location) }
        # locations_updated.push(rule_results[:location])
      end
    end
    
    @sudoku.save
    
    flash[:rules] = rules_used
    flash[:locations] = locations_updated
    flash[:rules_attempted] = true
    
    redirect_to sudoku_path(@sudoku)
  end
  
  def show
    @sudoku = Sudoku.find(params[:id])
    
    @just_created = flash[:just_created]
    @rules_attempted = flash[:rules_attempted]
    @rules_used = flash[:rules] || []
    @locations_updated = flash[:locations] || []
    flash.delete(:just_created)
    flash.delete(:rules)
    flash.delete(:locations)
    flash.delete(:rules_attempted)
  end
  
  def update
    @sudoku = Sudoku.find(params[:id])
    @sudoku.big_grid=[]
    81.times do |i|
      if (params[i.to_s].to_i)
        params[i.to_s].to_i > 0 ? @sudoku.big_grid[i]={ value: params[i.to_s].to_i } : @sudoku.big_grid[i]={}
      end
      
      # should find a way to not have to repeat these 2 lines - they are also in massage_grid in sudoku.rb
      @sudoku.big_grid[i][:location] = i
      @sudoku.big_grid[i][:possibilities] = []
    end
    
    @sudoku.save
    
    flash[:just_created] = true
    redirect_to sudoku_path(@sudoku)
  end
  
end

app/helpers/sudokus_helper.rb
module SudokusHelper
end

app/views/sudokus/_big_grid.html.erb
<div class="span4 offset1">

<table class="outer">
	<tr>
		<% 9.times do |i| %>
			<td>
				<table class="inner">
					<tr>
						<% j=0 %>
						<% @sudoku.cube_objects_by_number(i).each do |item| %>
							<td>
								<% if (@locations_updated.include?(item[:location])) %>
									<div class='newly-solved'>
								<% else %>
									<div>
								<% end %>
								
								<% if item[:value] %>
									<%= item[:value] %>
								<% elsif item[:possibilities] %>
									<div class='possibilities'>
										<% item[:possibilities].each do |possibility| %>
											<%= possibility %>
										<% end %>
									</div>
								<% end %>
								
								</div>
							</td>
							<% if (j==2 || j==5)%>
								</tr><tr>
							<% end %>
							<% j+=1 %>
						<% end %>
					</tr>
				</table>
			</td>
			<% if (i==2 || i==5)%>
				</tr><tr>
			<% end %>
		<% end %>
	</tr>
</table>

</div>

app/views/sudokus/_edit_big_grid.html.erb
<%= form_tag @sudoku, method: :put do %>

<div class="row" id="big_grid_table">
	<div class="span4 offset1">

		<table class="outer">
			<tr>
				<% 9.times do |i| %>
					<td>
						<table class="inner">
							<tr>
								<% j=0 %>
								<% @sudoku.cube_locations_by_number(i).each do |location| %>
									<td>
										<%= text_field_tag location%>
									</td>
									<% if (j==2 || j==5)%>
										</tr><tr>
									<% end %>
									<% j+=1 %>
								<% end %>
							</tr>
						</table>
					</td>
					<% if (i==2 || i==5)%>
						</tr><tr>
					<% end %>
				<% end %>
			</tr>
		</table>

	</div>
</div>

<%= submit_tag "Create Your Puzzle", class: "btn btn-large btn-primary" %>
	
<% end %>

app/views/sudokus/_rule_used.html.erb
<h4><%= rule_used %></h4>

app/views/sudokus/_solver_buttons.html.erb
<div class="row">
	<div class="span2 offset1">
		<%= form_tag solve_sudoku_path(@sudoku) do %>
	
			<%= submit_tag "Solve Next Number", class: "btn btn-large btn-primary" %>
			<%= hidden_field_tag "solve_this_many", 1 %>
	
		<% end %>
	</div>

	<div class="span2 offset1">
		<%= form_tag solve_sudoku_path(@sudoku) do %>
	
			<%= submit_tag "Solve Next 5 Numbers", class: "btn btn-large btn-primary" %>
			<%= hidden_field_tag "solve_this_many", 5 %>
	
		<% end %>
	</div>
	<div class="span2 offset1">
		<%= form_tag solve_sudoku_path(@sudoku) do %>
	
			<%= submit_tag "Solve Entire Puzzle", class: "btn btn-large btn-primary" %>
			<%= hidden_field_tag "solve_this_many", "all" %>
	
		<% end %>
	</div>
</div>

app/views/sudokus/edit.html.erb
<h3>Creating puzzle <%= @sudoku.content %></h3>
<%= render 'edit_big_grid' %>

app/views/sudokus/new.html.erb
<% provide(:title, 'Sudoku') %>
<h1>Sudoku Solver</h1>
<div class="row">
	<div class="span6 offset3">

		<%= form_for(@sudoku) do |f| %>
			<div id="error_explanation">
				<% @sudoku.errors.full_messages.each do |msg| %>
			      <li><%= msg %></li>
			    <% end %>
			</div>
					
			<%= f.label :content, "Name your puzzle" %>
			<%= f.text_field :content %>
						
<!--
		    <%= f.submit class: "btn btn-large btn-primary", value: "Original Puzzle" %>
			
			<%= f.submit class: "btn btn-large btn-primary", value: "Random Puzzle" %>			
			<%# the above button will automatically have name: "commit" included %>
			
			<%= f.submit class: "btn btn-large btn-primary", value: "Create Your Own" %>			
-->
		
			<button class="btn btn-large btn-primary" type="submit" name="create" value="original">Original Puzzle</button>
			<button class="btn btn-large btn-primary" type="submit" name="create" value="random">Random Puzzle</button>
			<button class="btn btn-large btn-primary" type="submit" name="create" value="new">Create Your Own</button>
		
		<% end %>
		
	</div>
</div>

app/views/sudokus/show.html.erb
<h3>Solving puzzle <%= @sudoku.content %></h3>

<div class="row" id="big_grid_table">
	<%= render 'big_grid' %>
	
	<div class="span8 offset0" id="rules-applied">	

		<% if @just_created %>
	
			<h3>Click buttons below to begin solving this puzzle!</h3>
	
		<% else %>
	
			<% if @rules_used.any? %>
				<h3>Rules applied:</h3>
				<%= render :partial => "rule_used", :collection => @rules_used %>
			<% elsif @rules_attempted && !@sudoku.solved %>
				<h3>This puzzle cannot be solved with basic rules!</h3>
				<!-- Reloading in the middle of solving breaks this logic -->
				<!-- Message also doesn't display if puzzle is impossible and 
				user clicks solve entire puzzle just once -->
			<% end %>

			<% if @sudoku.solved %>
				<h3>This puzzle is solved!</h3>
			<% end %>
	
		<% end %>

	</div>

</div>

<% if !@sudoku.solved %>
	<%= render 'solver_buttons' %>
<% end %>

<!-- Display big_grid for debugging purposes -->

<!-- <% if (@sudoku.big_grid) %>
	
	<% 81.times do |i| %>

		<% if ((i%9)==0) %>
			<br>
		<% end %>
		<% if (@sudoku.big_grid[i][:value]) %>
			<%= @sudoku.big_grid[i][:value] %>
		<% else %>
			0
		<% end %>
	<% end %>
<% else %>
	<%= "DNE" %>
<% end %> -->