config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sudokus do
    member do
      post :solve
    end
  end
  
  resources :sessions, only:      [:new, :create, :destroy]
  resources :microposts, only:    [:create, :destroy]
  resources :relationships, only: [:create, :destroy] 

  root to: 'static_pages#home'

  match '/sender', to: 'static_pages#sender'
  match '/test', to: 'static_pages#test', via: :post
  match '/record', to: 'static_pages#record', via: :post
  match '/maps',  to: 'static_pages#maps'
  match '/sudoku',  to: 'sudokus#new'
  match '/signup',  to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help' => 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/shared/_delete.html.erb
<%= link_to "delete", object, 	method: :delete,
								data: { confirm: "You sure?" },
								title: object.content %>
								
<%#---> not sure what the title: tag does -- removing it seems to have no effect; 
 removal is visible in the html, but link works just the same %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
			

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<%# @feed_items is created in the static pages controller%>

	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
<%# passing :collection parameter with the feed items causes render to use the given partial (’feed_item’ in this case) to render each item in the collection %>

	</ol>
	
	<%= will_paginate @feed_items %>
	
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
<%#---> creates a CSS id for each list item, but not sure why ... just for testing? %>

	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp">
		Posted at <%= feed_item.created_at.strftime("%X %p (UTC) on %x") %>
	</span>
	<%= render 'shared/delete', object: feed_item if current_user?(feed_item.user) %>
<%#---> don't know why this works but it doesn't work to say 'render partial' here %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>

	<%= render 'shared/error_messages', object: f.object %>
<%#---> figure out how to move this to somewhere more logical %>

<%# because we are in a form_for related to @microposts, f.object means @microposts %>

<%# if error_messages is a partial that's used here but nowhere else, 
# we can just use vars inside the partial called by render that are valid here.  
# BUT if we want to use error_messages in multiple places, 
# then we have to treat the render call not like it just 
# inserts code here, but like it is a real method that takes vars 
# and it takes them as a hash as in object: f.object %>

	<div class='field'>
		<%= f.text_area :content, placeholder: "Compose new micropost..." %>
	</div>

	<%= f.submit "Post", class: "btn btn-large btn-primary" %>

<% end %>

app/views/shared/_new_user_home.html.erb
<div class="center hero-unit">
	<h1>Welcome to Twutter</h1>
    <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>	

app/views/shared/_signed_in_home.html.erb
<div class="row">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
		<section>
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>
	<div class="span8">
		<h3>Micropost Feed</h3>
		<%= render 'shared/feed' %>
	</div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<%# needed b/c @user is nil on the home page%>

<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, size: 52 %>
</a>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "view my profile", current_user %>
</span>
<span class='mp'>
	<%= pluralize(current_user.microposts.count, "micropost") %>
<%# this provides the number and the label, properly pluralized %>
</span>